// SPDX-License-Identifier: MIT
// Copyright (c) 2026 TrendVidia, LLC.

package main

// SBE codegen — extends protoc-gen-pxf-java-meta with lite-tier SBE
// support. For each message that has the (sbe.template_id) option set,
// emits two companion files:
//
//   - <Message>SbeMeta.java — descriptor-free MessageTemplate baked
//     in as a static initializer, plus inline SbeFieldReader /
//     SbeFieldWriter implementations that dispatch field number to
//     the lite-Java typed getter/setter on the surrounding Message.
//
//   - <Message>SbeCodec.java — typed marshal(Foo) / unmarshal(byte[],
//     Foo.Builder) entry points composing the runtime's wire codec
//     with the meta's reader/writer factories.
//
// Together these eliminate the runtime descriptor reflection that the
// full-runtime :sbe Codec requires. Group-entry submessages (ones
// nested inside a templated message and labeled `repeated`) get their
// reader/writer logic emitted inline inside the parent's SbeMeta —
// they're not addressable on their own SbeCodec since users never
// marshal a group entry standalone.
//
// SBE template constraints (see :sbe TemplateBuilder for the source-
// of-truth rules; the same constraints apply here at codegen time):
//   - No map fields.
//   - No oneofs (synthetic proto3 optional ones are fine).
//   - No repeated scalar fields. `repeated <Submessage>` is the only
//     allowed repeated form (becomes an SBE group).
//   - String/bytes fields require (sbe.length).
//   - All other types use a default encoding derivable from the
//     proto type, optionally overridden by (sbe.encoding).

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/types/descriptorpb"
)

// emitSbeMeta generates <Message>SbeMeta.java for an SBE-templated
// message. Returns ("", false) if the message lacks (sbe.template_id).
func emitSbeMeta(
	file *descriptorpb.FileDescriptorProto,
	byName map[string]*descriptorpb.FileDescriptorProto,
	msg *flatMsg,
) (string, bool) {
	tid, hasTid := extUint32(msg.desc.GetOptions(), extSbeTemplateID)
	if !hasTid {
		return "", false
	}
	schemaID, _ := extUint32(file.GetOptions(), extSbeSchemaID)
	version, _ := extUint32(file.GetOptions(), extSbeVersion)

	cls := msg.classStem + "SbeMeta"
	javaPkg := file.GetOptions().GetJavaPackage()
	typedFqn := javaTypeName(byName, "."+qualifiedProtoName(file, msg))

	// Pre-compute the template layout so we can emit field offsets/sizes
	// as `static final int` constants and feed them to MessageTemplate.
	layout, err := buildSbeLayout(msg.desc, byName)
	if err != nil {
		return "// SbeMeta layout error: " + err.Error() + "\n", true
	}

	var b strings.Builder
	p := lineWriter(&b)

	p("// Generated by protoc-gen-pxf-java-meta (lite mode). DO NOT EDIT.")
	p("// source: ", file.GetName())
	p()
	p("package ", javaPkg, ";")
	p()
	p("import com.google.protobuf.ByteString;")
	p()
	p("import org.protowire.sbe.runtime.FieldTemplate;")
	p("import org.protowire.sbe.runtime.GroupTemplate;")
	p("import org.protowire.sbe.runtime.MessageTemplate;")
	p("import org.protowire.sbe.runtime.SbeFieldReader;")
	p("import org.protowire.sbe.runtime.SbeFieldWriter;")
	p("import org.protowire.sbe.runtime.ViewSchema;")
	p()
	p("import java.util.List;")
	p()
	p("/**")
	p(" * SBE template + typed reader/writer dispatch for {@code ", qualifiedProtoName(file, msg), "}.")
	p(" *")
	p(" * <p>The template lays out a ", layout.blockLength, "-byte root block; the wire codec ")
	p(" * (org.protowire.sbe.runtime.SbeWireCodec) reads/writes through the reader/writer ")
	p(" * factories, which call the lite-Java typed getters/setters on the message.")
	p(" */")
	p("public final class ", cls, " {")
	p("    private ", cls, "() {}")
	p()
	p("    /** {@code (sbe.schema_id)} value, or 0 if unset on the file. */")
	p("    public static final int SCHEMA_ID = ", schemaID, ";")
	p("    /** {@code (sbe.version)} value, or 0 if unset on the file. */")
	p("    public static final int VERSION = ", version, ";")
	p()
	p("    public static final MessageTemplate TEMPLATE;")
	p("    static {")
	emitTemplateInitializer(p, &layout, "        ")
	p("    }")
	p()
	p("    /** Wraps a typed {@code ", typedFqn, "} as an {@link SbeFieldReader}. */")
	p("    public static SbeFieldReader reader(", typedFqn, " msg) {")
	p("        return new Reader(msg);")
	p("    }")
	p()
	p("    /** Wraps a typed {@code ", typedFqn, ".Builder} as an {@link SbeFieldWriter}. */")
	p("    public static SbeFieldWriter writer(", typedFqn, ".Builder b) {")
	p("        return new Writer(b);")
	p("    }")
	p()
	emitSbeReaderClass(p, "Reader", typedFqn, &layout, msg, byName)
	p()
	emitSbeWriterClass(p, "Writer", typedFqn, &layout, msg, byName)
	emitSbeGroupHelpers(p, typedFqn, &layout, msg, byName)
	emitSbeCompositeHelpers(p, &layout, byName)
	p("}")

	_ = tid
	_ = schemaID
	_ = version
	return b.String(), true
}

// emitSbeCodec generates <Message>SbeCodec.java — the typed convenience
// wrapper composing SbeWireCodec.{marshal,unmarshal} with the meta's
// reader/writer factories.
func emitSbeCodec(
	file *descriptorpb.FileDescriptorProto,
	byName map[string]*descriptorpb.FileDescriptorProto,
	msg *flatMsg,
) (string, bool) {
	if _, has := extUint32(msg.desc.GetOptions(), extSbeTemplateID); !has {
		return "", false
	}
	cls := msg.classStem + "SbeCodec"
	metaCls := msg.classStem + "SbeMeta"
	javaPkg := file.GetOptions().GetJavaPackage()
	typedFqn := javaTypeName(byName, "."+qualifiedProtoName(file, msg))

	var b strings.Builder
	p := lineWriter(&b)

	p("// Generated by protoc-gen-pxf-java-meta (lite mode). DO NOT EDIT.")
	p("// source: ", file.GetName())
	p()
	p("package ", javaPkg, ";")
	p()
	p("import org.protowire.sbe.runtime.SbeWireCodec;")
	p()
	p("/**")
	p(" * Typed convenience wrappers around the lite-runtime SBE wire codec for")
	p(" * {@code ", qualifiedProtoName(file, msg), "}.")
	p(" *")
	p(" * <ul>")
	p(" *   <li>{@link #marshal(", typedFqn, ")}: typed message → SBE wire bytes.</li>")
	p(" *   <li>{@link #unmarshal(byte[], ", typedFqn, ".Builder)}: SBE wire bytes → builder.</li>")
	p(" * </ul>")
	p(" */")
	p("public final class ", cls, " {")
	p("    private ", cls, "() {}")
	p()
	p("    /** Serialize {@code msg} to SBE wire bytes. */")
	p("    public static byte[] marshal(", typedFqn, " msg) {")
	p("        return SbeWireCodec.marshal(", metaCls, ".reader(msg), ", metaCls, ".TEMPLATE);")
	p("    }")
	p()
	p("    /** Deserialize SBE wire bytes into {@code b}. */")
	p("    public static void unmarshal(byte[] data, ", typedFqn, ".Builder b) {")
	p("        SbeWireCodec.unmarshal(data, ", metaCls, ".writer(b), ", metaCls, ".TEMPLATE);")
	p("    }")
	p()
	p("    /** Convenience: parse into a fresh builder, return the built message. */")
	p("    public static ", typedFqn, " unmarshal(byte[] data) {")
	p("        ", typedFqn, ".Builder b = ", typedFqn, ".newBuilder();")
	p("        unmarshal(data, b);")
	p("        return b.build();")
	p("    }")
	p("}")
	return b.String(), true
}

// --- Layout computation -----------------------------------------------------
//
// Mirrors :sbe TemplateBuilder's layout pass at codegen time. Field
// offsets, sizes, and encodings are baked into the emitted SbeMeta so
// the runtime never re-derives them.

type sbeFieldLayout struct {
	field       *descriptorpb.FieldDescriptorProto
	fieldNumber int32
	name        string
	kind        int32  // FieldDescriptorProto.Type integer
	offset      int
	size        int
	encoding    string // empty for composite
	composite   *sbeCompositeLayout
}

type sbeCompositeLayout struct {
	typeName  string // proto FQN of the composite submessage
	totalSize int
	fields    []sbeFieldLayout
}

type sbeGroupLayout struct {
	field       *descriptorpb.FieldDescriptorProto
	fieldNumber int32
	name        string
	blockLength int
	fields      []sbeFieldLayout
}

type sbeMessageLayout struct {
	templateID  uint32
	schemaID    uint32
	version     uint32
	blockLength int
	fields      []sbeFieldLayout
	groups      []sbeGroupLayout
}

func buildSbeLayout(
	md *descriptorpb.DescriptorProto,
	byName map[string]*descriptorpb.FileDescriptorProto,
) (sbeMessageLayout, error) {
	tid, hasTid := extUint32(md.GetOptions(), extSbeTemplateID)
	if !hasTid {
		return sbeMessageLayout{}, fmt.Errorf("message %q missing (sbe.template_id)", md.GetName())
	}
	// schema_id / version live at file scope; the caller resolves them
	// when emitting the template literal.
	out := sbeMessageLayout{templateID: tid}

	offset := 0
	for _, f := range sortedSbeFields(md) {
		if isMapField(f, byName) {
			return out, fmt.Errorf("sbe: map field %q not supported", f.GetName())
		}
		if f.OneofIndex != nil && !isSyntheticSbeOneof(md, int(*f.OneofIndex)) {
			return out, fmt.Errorf("sbe: oneof field %q not supported", f.GetName())
		}
		isRepeated := f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED
		isMessage := f.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE
		if isRepeated && isMessage {
			gt, err := buildSbeGroup(f, byName)
			if err != nil {
				return out, err
			}
			out.groups = append(out.groups, gt)
			continue
		}
		if isRepeated {
			return out, fmt.Errorf("sbe: repeated scalar %q not supported", f.GetName())
		}
		if isMessage {
			subDesc := findMessage(byName, strings.TrimPrefix(f.GetTypeName(), "."))
			if subDesc == nil {
				return out, fmt.Errorf("sbe: composite type %q not found", f.GetTypeName())
			}
			composite, err := buildSbeComposite(subDesc, byName)
			if err != nil {
				return out, err
			}
			composite.typeName = strings.TrimPrefix(f.GetTypeName(), ".")
			out.fields = append(out.fields, sbeFieldLayout{
				field:       f,
				fieldNumber: f.GetNumber(),
				name:        f.GetName(),
				kind:        int32(f.GetType()),
				offset:      offset,
				size:        composite.totalSize,
				composite:   composite,
			})
			offset += composite.totalSize
			continue
		}
		enc, sz, err := sbeFieldEncoding(f)
		if err != nil {
			return out, err
		}
		out.fields = append(out.fields, sbeFieldLayout{
			field:       f,
			fieldNumber: f.GetNumber(),
			name:        f.GetName(),
			kind:        int32(f.GetType()),
			offset:      offset,
			size:        sz,
			encoding:    enc,
		})
		offset += sz
	}
	out.blockLength = offset
	return out, nil
}

func buildSbeGroup(
	f *descriptorpb.FieldDescriptorProto,
	byName map[string]*descriptorpb.FileDescriptorProto,
) (sbeGroupLayout, error) {
	subDesc := findMessage(byName, strings.TrimPrefix(f.GetTypeName(), "."))
	if subDesc == nil {
		return sbeGroupLayout{}, fmt.Errorf("sbe: group type %q not found", f.GetTypeName())
	}
	out := sbeGroupLayout{
		field:       f,
		fieldNumber: f.GetNumber(),
		name:        f.GetName(),
	}
	offset := 0
	for _, gf := range sortedSbeFields(subDesc) {
		if gf.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED || isMapField(gf, byName) {
			return out, fmt.Errorf("sbe: nested repeated/map in group %q", subDesc.GetName())
		}
		if gf.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			composite, err := buildSbeComposite(
				findMessage(byName, strings.TrimPrefix(gf.GetTypeName(), ".")), byName)
			if err != nil {
				return out, err
			}
			composite.typeName = strings.TrimPrefix(gf.GetTypeName(), ".")
			out.fields = append(out.fields, sbeFieldLayout{
				field: gf, fieldNumber: gf.GetNumber(), name: gf.GetName(),
				kind: int32(gf.GetType()), offset: offset, size: composite.totalSize,
				composite: composite,
			})
			offset += composite.totalSize
			continue
		}
		enc, sz, err := sbeFieldEncoding(gf)
		if err != nil {
			return out, err
		}
		out.fields = append(out.fields, sbeFieldLayout{
			field: gf, fieldNumber: gf.GetNumber(), name: gf.GetName(),
			kind: int32(gf.GetType()), offset: offset, size: sz, encoding: enc,
		})
		offset += sz
	}
	out.blockLength = offset
	return out, nil
}

func buildSbeComposite(
	md *descriptorpb.DescriptorProto,
	byName map[string]*descriptorpb.FileDescriptorProto,
) (*sbeCompositeLayout, error) {
	out := &sbeCompositeLayout{}
	offset := 0
	for _, f := range sortedSbeFields(md) {
		if f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED || isMapField(f, byName) {
			return nil, fmt.Errorf("sbe: composite contains list/map field %q", f.GetName())
		}
		if f.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			sub, err := buildSbeComposite(
				findMessage(byName, strings.TrimPrefix(f.GetTypeName(), ".")), byName)
			if err != nil {
				return nil, err
			}
			sub.typeName = strings.TrimPrefix(f.GetTypeName(), ".")
			out.fields = append(out.fields, sbeFieldLayout{
				field: f, fieldNumber: f.GetNumber(), name: f.GetName(),
				kind: int32(f.GetType()), offset: offset, size: sub.totalSize,
				composite: sub,
			})
			offset += sub.totalSize
			continue
		}
		enc, sz, err := sbeFieldEncoding(f)
		if err != nil {
			return nil, err
		}
		out.fields = append(out.fields, sbeFieldLayout{
			field: f, fieldNumber: f.GetNumber(), name: f.GetName(),
			kind: int32(f.GetType()), offset: offset, size: sz, encoding: enc,
		})
		offset += sz
	}
	out.totalSize = offset
	return out, nil
}

// sbeFieldEncoding mirrors :sbe TemplateBuilder.fieldEncodingSize.
func sbeFieldEncoding(f *descriptorpb.FieldDescriptorProto) (string, int, error) {
	if override, ok := extString(f.GetOptions(), extSbeFieldEncode); ok && override != "" {
		switch override {
		case "int8", "uint8":
			return override, 1, nil
		case "int16", "uint16":
			return override, 2, nil
		case "int32", "uint32", "float":
			return override, 4, nil
		case "int64", "uint64", "double":
			return override, 8, nil
		default:
			return "", 0, fmt.Errorf("unknown sbe encoding: %s", override)
		}
	}
	switch f.GetType() {
	case descriptorpb.FieldDescriptorProto_TYPE_BOOL:
		return "uint8", 1, nil
	case descriptorpb.FieldDescriptorProto_TYPE_INT32,
		descriptorpb.FieldDescriptorProto_TYPE_SINT32,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED32:
		return "int32", 4, nil
	case descriptorpb.FieldDescriptorProto_TYPE_INT64,
		descriptorpb.FieldDescriptorProto_TYPE_SINT64,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED64:
		return "int64", 8, nil
	case descriptorpb.FieldDescriptorProto_TYPE_UINT32,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED32:
		return "uint32", 4, nil
	case descriptorpb.FieldDescriptorProto_TYPE_UINT64,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED64:
		return "uint64", 8, nil
	case descriptorpb.FieldDescriptorProto_TYPE_FLOAT:
		return "float", 4, nil
	case descriptorpb.FieldDescriptorProto_TYPE_DOUBLE:
		return "double", 8, nil
	case descriptorpb.FieldDescriptorProto_TYPE_ENUM:
		return "uint8", 1, nil
	case descriptorpb.FieldDescriptorProto_TYPE_STRING,
		descriptorpb.FieldDescriptorProto_TYPE_BYTES:
		length, ok := extUint32(f.GetOptions(), extSbeFieldLength)
		if !ok {
			return "", 0, fmt.Errorf("string/bytes field %q requires (sbe.length)", f.GetName())
		}
		return "char", int(length), nil
	default:
		return "", 0, fmt.Errorf("unsupported proto type for sbe: %s", f.GetType())
	}
}

func sortedSbeFields(md *descriptorpb.DescriptorProto) []*descriptorpb.FieldDescriptorProto {
	out := make([]*descriptorpb.FieldDescriptorProto, len(md.Field))
	copy(out, md.Field)
	// Stable sort by field number.
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j-1].GetNumber() > out[j].GetNumber(); j-- {
			out[j-1], out[j] = out[j], out[j-1]
		}
	}
	return out
}

// isSyntheticSbeOneof inlined here to avoid a dep on isSyntheticOneof's
// exact location; uses the same heuristic.
func isSyntheticSbeOneof(msg *descriptorpb.DescriptorProto, idx int) bool {
	var members []*descriptorpb.FieldDescriptorProto
	for _, f := range msg.Field {
		if f.OneofIndex != nil && int(*f.OneofIndex) == idx {
			members = append(members, f)
		}
	}
	return len(members) == 1 && members[0].GetProto3Optional()
}

// --- Template literal emission ---------------------------------------------

func emitTemplateInitializer(p func(args ...any), m *sbeMessageLayout, indent string) {
	// schema_id / version come from the file-scope options; default to 0
	// when unset (matching the runtime's `version == null ? 0 : version`).
	p(indent, "TEMPLATE = new MessageTemplate(")
	p(indent, "    /* templateId  */ ", m.templateID, ",")
	p(indent, "    /* schemaId    */ ", "SCHEMA_ID", ",")
	p(indent, "    /* version     */ ", "VERSION", ",")
	p(indent, "    /* blockLength */ ", m.blockLength, ",")
	if len(m.fields) == 0 {
		p(indent, "    /* fields      */ List.of(),")
	} else {
		p(indent, "    /* fields      */ List.of(")
		emitFieldList(p, m.fields, indent+"        ")
		p(indent, "    ),")
	}
	if len(m.groups) == 0 {
		p(indent, "    /* groups      */ List.of(),")
	} else {
		p(indent, "    /* groups      */ List.of(")
		for i, g := range m.groups {
			emitGroupTemplate(p, g, indent+"        ", i == len(m.groups)-1)
		}
		p(indent, "    ),")
	}
	p(indent, "    /* viewSchema  */ null /* unused for marshal/unmarshal path */")
	p(indent, ");")
}

func emitFieldList(p func(args ...any), fields []sbeFieldLayout, indent string) {
	for i, f := range fields {
		emitFieldTemplate(p, f, indent, i == len(fields)-1)
	}
}

func emitFieldTemplate(p func(args ...any), f sbeFieldLayout, indent string, last bool) {
	tail := ","
	if last {
		tail = ""
	}
	composite := "null"
	if f.composite != nil {
		var sb strings.Builder
		sb.WriteString("List.of(")
		for i, sub := range f.composite.fields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf(
				"new FieldTemplate(%d, %q, %d, %d, %d, %q, %s)",
				sub.fieldNumber, sub.name, sub.kind, sub.offset, sub.size, sub.encoding,
				renderCompositeInline(sub.composite),
			))
		}
		sb.WriteString(")")
		composite = sb.String()
	}
	p(indent, "new FieldTemplate(", f.fieldNumber, ", ", quoteJava(f.name), ", ", f.kind,
		", ", f.offset, ", ", f.size, ", ", quoteJava(f.encoding), ", ", composite, ")", tail)
}

func renderCompositeInline(c *sbeCompositeLayout) string {
	if c == nil {
		return "null"
	}
	var sb strings.Builder
	sb.WriteString("List.of(")
	for i, sub := range c.fields {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf(
			"new FieldTemplate(%d, %q, %d, %d, %d, %q, %s)",
			sub.fieldNumber, sub.name, sub.kind, sub.offset, sub.size, sub.encoding,
			renderCompositeInline(sub.composite),
		))
	}
	sb.WriteString(")")
	return sb.String()
}

func emitGroupTemplate(p func(args ...any), g sbeGroupLayout, indent string, last bool) {
	tail := ","
	if last {
		tail = ""
	}
	p(indent, "new GroupTemplate(", g.fieldNumber, ", ", quoteJava(g.name),
		", ", g.blockLength, ", List.of(")
	for i, f := range g.fields {
		emitFieldTemplate(p, f, indent+"    ", i == len(g.fields)-1)
	}
	p(indent, "))", tail)
}

// --- Reader / Writer emission ----------------------------------------------

func emitSbeReaderClass(
	p func(args ...any),
	cls string,
	typedFqn string,
	layout *sbeMessageLayout,
	msg *flatMsg,
	byName map[string]*descriptorpb.FileDescriptorProto,
) {
	p("    private static final class ", cls, " implements SbeFieldReader {")
	p("        private final ", typedFqn, " msg;")
	p("        ", cls, "(", typedFqn, " msg) { this.msg = msg; }")
	p()
	// getField — non-message scalars + composites (composites read as a sub-reader,
	// but routed via getMessageField, so getField only handles scalars/string/bytes/enum).
	p("        @Override public Object getField(int fieldNumber) {")
	p("            return switch (fieldNumber) {")
	for _, f := range layout.fields {
		if f.composite != nil {
			continue
		}
		p("                case ", f.fieldNumber, " -> msg.", javaScalarGetter(f), ";")
	}
	p("                default -> throw new IllegalArgumentException(",
		quoteJava("sbe: unknown field number "), " + fieldNumber);")
	p("            };")
	p("        }")
	p()
	// getMessageField — composite (non-repeated MESSAGE) fields. The wire
	// codec only calls this when ft.composite != null in the template; non-
	// composite cases reach here only through caller error.
	emitCompositeFieldGetterDispatch(p, layout.fields, byName, "        ")
	p()
	// getRepeatedCount + getRepeatedMessage — groups.
	p("        @Override public int getRepeatedCount(int fieldNumber) {")
	p("            return switch (fieldNumber) {")
	for _, g := range layout.groups {
		p("                case ", g.fieldNumber, " -> msg.get", javaPascalName(g.name), "Count();")
	}
	p("                default -> throw new IllegalArgumentException(",
		quoteJava("sbe: no repeated field at "), " + fieldNumber);")
	p("            };")
	p("        }")
	p()
	p("        @Override public SbeFieldReader getRepeatedMessage(int fieldNumber, int index) {")
	p("            return switch (fieldNumber) {")
	for _, g := range layout.groups {
		readerCls := "GroupReader_" + javaPascalName(g.name)
		p("                case ", g.fieldNumber, " -> new ", readerCls,
			"(msg.get", javaPascalName(g.name), "(index));")
	}
	p("                default -> throw new IllegalArgumentException(",
		quoteJava("sbe: no repeated field at "), " + fieldNumber);")
	p("            };")
	p("        }")
	p("    }")
	_ = msg
	_ = byName
}

// emitSbeWriterClass writes the top-level Writer for a templated message.
// Group-entry writers are handled by emitSbeGroupHelpers — they need a
// reference back to the parent builder for commit(), which only makes
// sense in that context.
func emitSbeWriterClass(
	p func(args ...any),
	cls string,
	typedFqn string,
	layout *sbeMessageLayout,
	msg *flatMsg,
	byName map[string]*descriptorpb.FileDescriptorProto,
) {
	p("    private static final class ", cls, " implements SbeFieldWriter {")
	p("        private final ", typedFqn, ".Builder b;")
	p("        ", cls, "(", typedFqn, ".Builder b) { this.b = b; }")
	p()
	p("        @Override public void setField(int fieldNumber, Object value) {")
	p("            switch (fieldNumber) {")
	for _, f := range layout.fields {
		if f.composite != nil {
			continue
		}
		p("                case ", f.fieldNumber, " -> b.",
			javaScalarSetter(f, "value"), ";")
	}
	p("                default -> throw new IllegalArgumentException(",
		quoteJava("sbe: unknown field number "), " + fieldNumber);")
	p("            }")
	p("        }")
	p()
	emitCompositeBuilderDispatch(p, layout.fields, byName, "b", "        ")
	p()
	p("        @Override public SbeFieldWriter newGroupEntry(int fieldNumber) {")
	p("            return switch (fieldNumber) {")
	for _, g := range layout.groups {
		entryFqn := sbeGroupEntryTypedFqn(typedFqn, g)
		writerCls := "GroupWriter_" + javaPascalName(g.name)
		p("                case ", g.fieldNumber, " -> new ", writerCls,
			"(b, ", entryFqn, ".newBuilder());")
	}
	p("                default -> throw new IllegalArgumentException(",
		quoteJava("sbe: no repeated field at "), " + fieldNumber);")
	p("            };")
	p("        }")
	p()
	p("        @Override public void commit() { /* top-level: no-op */ }")
	p("    }")
	_ = msg
	_ = byName
}

// emitSbeGroupHelpers writes the inline reader/writer classes for each
// group entry plus the composite reader/writer classes. Group entries
// aren't templated themselves, so they don't get their own SbeMeta.
func emitSbeGroupHelpers(
	p func(args ...any),
	parentFqn string,
	layout *sbeMessageLayout,
	msg *flatMsg,
	byName map[string]*descriptorpb.FileDescriptorProto,
) {
	for _, g := range layout.groups {
		entryFqn := sbeGroupEntryTypedFqn(parentFqn, g)
		readerCls := "GroupReader_" + javaPascalName(g.name)
		writerCls := "GroupWriter_" + javaPascalName(g.name)
		// Reader.
		p()
		p("    private static final class ", readerCls, " implements SbeFieldReader {")
		p("        private final ", entryFqn, " msg;")
		p("        ", readerCls, "(", entryFqn, " msg) { this.msg = msg; }")
		p("        @Override public Object getField(int fieldNumber) {")
		p("            return switch (fieldNumber) {")
		for _, f := range g.fields {
			if f.composite != nil {
				continue
			}
			p("                case ", f.fieldNumber, " -> msg.", javaScalarGetter(f), ";")
		}
		p("                default -> throw new IllegalArgumentException(",
			quoteJava("sbe: unknown field number "), " + fieldNumber);")
		p("            };")
		p("        }")
		emitCompositeFieldGetterDispatch(p, g.fields, byName, "        ")
		p("        @Override public int getRepeatedCount(int fieldNumber) {")
		p("            throw new IllegalArgumentException(", quoteJava("sbe: no repeated field in group "), ");")
		p("        }")
		p("        @Override public SbeFieldReader getRepeatedMessage(int fieldNumber, int index) {")
		p("            throw new IllegalArgumentException(", quoteJava("sbe: no repeated field in group "), ");")
		p("        }")
		p("    }")
		// Writer.
		p()
		p("    private static final class ", writerCls, " implements SbeFieldWriter {")
		p("        private final ", parentFqn, ".Builder parent;")
		p("        private final ", entryFqn, ".Builder b;")
		p("        ", writerCls, "(", parentFqn, ".Builder parent, ", entryFqn, ".Builder b) {")
		p("            this.parent = parent;")
		p("            this.b = b;")
		p("        }")
		p("        @Override public void setField(int fieldNumber, Object value) {")
		p("            switch (fieldNumber) {")
		for _, f := range g.fields {
			if f.composite != nil {
				continue
			}
			p("                case ", f.fieldNumber, " -> b.",
				javaScalarSetter(f, "value"), ";")
		}
		p("                default -> throw new IllegalArgumentException(",
			quoteJava("sbe: unknown field number "), " + fieldNumber);")
		p("            }")
		p("        }")
		emitCompositeBuilderDispatch(p, g.fields, byName, "b", "        ")
		p("        @Override public SbeFieldWriter newGroupEntry(int fieldNumber) {")
		p("            throw new IllegalArgumentException(", quoteJava("sbe: no nested group "), ");")
		p("        }")
		p("        @Override public void commit() {")
		p("            parent.add", javaPascalName(g.name), "(b.build());")
		p("        }")
		p("    }")
	}
	_ = msg
	_ = byName
}

// --- Composite read/write emit ---------------------------------------------

// emitCompositeFieldGetterDispatch writes the SbeFieldReader#getMessageField
// override, dispatching to a CompositeReader_<simpleName> per composite
// field in `fields`. Throws on non-composite calls.
func emitCompositeFieldGetterDispatch(
	p func(args ...any),
	fields []sbeFieldLayout,
	byName map[string]*descriptorpb.FileDescriptorProto,
	indent string,
) {
	hasComposite := false
	for _, f := range fields {
		if f.composite != nil {
			hasComposite = true
			break
		}
	}
	p(indent, "@Override public SbeFieldReader getMessageField(int fieldNumber) {")
	if !hasComposite {
		p(indent, "    throw new IllegalArgumentException(",
			quoteJava("sbe: no composite at "), " + fieldNumber);")
		p(indent, "}")
		return
	}
	p(indent, "    return switch (fieldNumber) {")
	for _, f := range fields {
		if f.composite == nil {
			continue
		}
		simple := simpleClassName(javaTypeName(byName, "."+f.composite.typeName))
		p(indent, "        case ", f.fieldNumber, " -> new CompositeReader_",
			simple, "(msg.get", javaPascalName(f.name), "());")
	}
	p(indent, "        default -> throw new IllegalArgumentException(",
		quoteJava("sbe: no composite at "), " + fieldNumber);")
	p(indent, "    };")
	p(indent, "}")
}

// emitCompositeBuilderDispatch writes the SbeFieldWriter#newMessageBuilder
// override, dispatching to a CompositeWriter_<simpleName> per composite
// field in `fields`. The builder local-var name is parameterized
// (`builderVar`) so this works for both the top-level `b` and group-entry
// builders that also use `b`.
func emitCompositeBuilderDispatch(
	p func(args ...any),
	fields []sbeFieldLayout,
	byName map[string]*descriptorpb.FileDescriptorProto,
	builderVar string,
	indent string,
) {
	hasComposite := false
	for _, f := range fields {
		if f.composite != nil {
			hasComposite = true
			break
		}
	}
	p(indent, "@Override public SbeFieldWriter newMessageBuilder(int fieldNumber) {")
	if !hasComposite {
		p(indent, "    throw new IllegalArgumentException(",
			quoteJava("sbe: no composite at "), " + fieldNumber);")
		p(indent, "}")
		return
	}
	p(indent, "    return switch (fieldNumber) {")
	for _, f := range fields {
		if f.composite == nil {
			continue
		}
		simple := simpleClassName(javaTypeName(byName, "."+f.composite.typeName))
		// The Consumer<T> callback handles parent-side commit. The lambda
		// captures `builderVar` and calls its typed setter on commit().
		p(indent, "        case ", f.fieldNumber, " -> new CompositeWriter_",
			simple, "(", builderVar, "::set", javaPascalName(f.name), ");")
	}
	p(indent, "        default -> throw new IllegalArgumentException(",
		quoteJava("sbe: no composite at "), " + fieldNumber);")
	p(indent, "    };")
	p(indent, "}")
}

// emitSbeCompositeHelpers writes one CompositeReader_<simpleName> +
// CompositeWriter_<simpleName> class per unique composite type in the
// layout (recursively walking nested composites). The reader takes the
// typed sub-message; the writer takes a Consumer<T> callback that commits
// the built sub-message back to whatever parent owns it.
func emitSbeCompositeHelpers(
	p func(args ...any),
	layout *sbeMessageLayout,
	byName map[string]*descriptorpb.FileDescriptorProto,
) {
	composites := collectComposites(layout, byName)
	for _, c := range composites {
		readerCls := "CompositeReader_" + c.simpleName
		writerCls := "CompositeWriter_" + c.simpleName
		// Reader.
		p()
		p("    private static final class ", readerCls, " implements SbeFieldReader {")
		p("        private final ", c.javaFqn, " msg;")
		p("        ", readerCls, "(", c.javaFqn, " msg) { this.msg = msg; }")
		p("        @Override public Object getField(int fieldNumber) {")
		p("            return switch (fieldNumber) {")
		for _, f := range c.layout.fields {
			if f.composite != nil {
				continue
			}
			p("                case ", f.fieldNumber, " -> msg.", javaScalarGetter(f), ";")
		}
		p("                default -> throw new IllegalArgumentException(",
			quoteJava("sbe: unknown field number "), " + fieldNumber);")
		p("            };")
		p("        }")
		emitCompositeFieldGetterDispatch(p, c.layout.fields, byName, "        ")
		p("        @Override public int getRepeatedCount(int fieldNumber) {")
		p("            throw new IllegalArgumentException(", quoteJava("sbe: no repeated field in composite "), ");")
		p("        }")
		p("        @Override public SbeFieldReader getRepeatedMessage(int fieldNumber, int index) {")
		p("            throw new IllegalArgumentException(", quoteJava("sbe: no repeated field in composite "), ");")
		p("        }")
		p("    }")
		// Writer.
		p()
		p("    private static final class ", writerCls, " implements SbeFieldWriter {")
		p("        private final java.util.function.Consumer<", c.javaFqn, "> onCommit;")
		p("        private final ", c.javaFqn, ".Builder b = ", c.javaFqn, ".newBuilder();")
		p("        ", writerCls, "(java.util.function.Consumer<", c.javaFqn, "> onCommit) {")
		p("            this.onCommit = onCommit;")
		p("        }")
		p("        @Override public void setField(int fieldNumber, Object value) {")
		p("            switch (fieldNumber) {")
		for _, f := range c.layout.fields {
			if f.composite != nil {
				continue
			}
			p("                case ", f.fieldNumber, " -> b.",
				javaScalarSetter(f, "value"), ";")
		}
		p("                default -> throw new IllegalArgumentException(",
			quoteJava("sbe: unknown field number "), " + fieldNumber);")
		p("            }")
		p("        }")
		emitCompositeBuilderDispatch(p, c.layout.fields, byName, "b", "        ")
		p("        @Override public SbeFieldWriter newGroupEntry(int fieldNumber) {")
		p("            throw new IllegalArgumentException(", quoteJava("sbe: no group entry in composite "), ");")
		p("        }")
		p("        @Override public void commit() {")
		p("            onCommit.accept(b.build());")
		p("        }")
		p("    }")
	}
}

// compositeTypeInfo describes one unique composite type referenced by the
// layout — used to drive emitSbeCompositeHelpers.
type compositeTypeInfo struct {
	typeName   string // proto FQN, e.g. "bench.v1.NewOrderSingle.LimitPrice"
	javaFqn    string // Java FQN, e.g. "bench.v1.NewOrderSingle.LimitPrice"
	simpleName string // last "." segment, used as the inline-class basename
	layout     *sbeCompositeLayout
}

// collectComposites walks layout.fields, layout.groups[*].fields, and
// every composite's recursive sub-fields, returning one entry per unique
// composite typeName encountered. Order doesn't matter to javac (the
// helpers reference each other by name within the same enclosing class).
func collectComposites(
	layout *sbeMessageLayout,
	byName map[string]*descriptorpb.FileDescriptorProto,
) []compositeTypeInfo {
	seen := make(map[string]bool)
	var out []compositeTypeInfo
	var walk func(fields []sbeFieldLayout)
	walk = func(fields []sbeFieldLayout) {
		for _, f := range fields {
			if f.composite == nil || seen[f.composite.typeName] {
				continue
			}
			seen[f.composite.typeName] = true
			javaFqn := javaTypeName(byName, "."+f.composite.typeName)
			out = append(out, compositeTypeInfo{
				typeName:   f.composite.typeName,
				javaFqn:    javaFqn,
				simpleName: simpleClassName(javaFqn),
				layout:     f.composite,
			})
			walk(f.composite.fields)
		}
	}
	walk(layout.fields)
	for _, g := range layout.groups {
		walk(g.fields)
	}
	return out
}

func simpleClassName(javaFqn string) string {
	if i := strings.LastIndex(javaFqn, "."); i >= 0 {
		return javaFqn[i+1:]
	}
	return javaFqn
}

// --- Naming helpers ---------------------------------------------------------

// javaPascalName converts snake_case to UpperCamelCase, the convention
// protoc-gen-java uses for class and accessor names.
func javaPascalName(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// javaScalarGetter returns the typed getter call for one field, including
// argument-less parens. ENUM uses getXValue() so we get the int back; the
// SbeFieldReader contract says ENUM yields Integer.
func javaScalarGetter(f sbeFieldLayout) string {
	name := javaPascalName(f.name)
	switch descriptorpb.FieldDescriptorProto_Type(f.kind) {
	case descriptorpb.FieldDescriptorProto_TYPE_ENUM:
		return "get" + name + "Value()"
	default:
		return "get" + name + "()"
	}
}

// javaCompositeGetter returns the typed sub-message getter for a
// composite field (always plain getX(), no Value suffix).
func javaCompositeGetter(f sbeFieldLayout) string {
	return "get" + javaPascalName(f.name) + "()"
}

// javaScalarSetter returns the typed setter call body, given the source
// value expression `valueExpr`. ENUM uses setXValue(int); the rest cast
// through the appropriate primitive wrapper.
func javaScalarSetter(f sbeFieldLayout, valueExpr string) string {
	name := javaPascalName(f.name)
	switch descriptorpb.FieldDescriptorProto_Type(f.kind) {
	case descriptorpb.FieldDescriptorProto_TYPE_ENUM:
		return fmt.Sprintf("set%sValue((Integer) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_BOOL:
		return fmt.Sprintf("set%s((Boolean) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_INT32,
		descriptorpb.FieldDescriptorProto_TYPE_SINT32,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED32,
		descriptorpb.FieldDescriptorProto_TYPE_UINT32,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED32:
		return fmt.Sprintf("set%s((Integer) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_INT64,
		descriptorpb.FieldDescriptorProto_TYPE_SINT64,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED64,
		descriptorpb.FieldDescriptorProto_TYPE_UINT64,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED64:
		return fmt.Sprintf("set%s((Long) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_FLOAT:
		return fmt.Sprintf("set%s((Float) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_DOUBLE:
		return fmt.Sprintf("set%s((Double) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_STRING:
		return fmt.Sprintf("set%s((String) %s)", name, valueExpr)
	case descriptorpb.FieldDescriptorProto_TYPE_BYTES:
		return fmt.Sprintf("set%s((ByteString) %s)", name, valueExpr)
	default:
		return fmt.Sprintf("set%s(%s)", name, valueExpr)
	}
}

// nestedJavaName concatenates an outer FQN with a nested simple name.
// e.g. ("com.foo.Outer", "Inner") -> "com.foo.Outer.Inner".
func nestedJavaName(outer, inner string) string {
	return outer + "." + inner
}

// sbeGroupEntryTypedFqn resolves the typed Java FQN of a group entry
// submessage. For a `repeated Fill fills = 6;` field on
// `com.foo.NewOrderSingle`, the entry type is `com.foo.NewOrderSingle.Fill`
// (nested) — we look it up via the descriptor's TypeName by stripping the
// parent's proto FQN prefix and treating the remainder as a nested name
// chain.
func sbeGroupEntryTypedFqn(parentFqn string, g sbeGroupLayout) string {
	tn := strings.TrimPrefix(g.field.GetTypeName(), ".")
	// Last segment of the proto FQN — e.g. "Fill" from "sbe.test.NewOrderSingle.Fill".
	lastDot := strings.LastIndexByte(tn, '.')
	simple := tn
	if lastDot >= 0 {
		simple = tn[lastDot+1:]
	}
	return nestedJavaName(parentFqn, simple)
}

